package edu.ung.phys;

import processing.core.PApplet;

import java.util.ArrayList;

/**
 * @author naharrison
 * for testing the mnist array convention
 * top left pixel is index 0, bottom right is indes 783
 * index increases like reading a book
 */
public class DisplayMNistImage extends PApplet {

	public static void main(String[] args) {
		PApplet.main("edu.ung.phys.DisplayMNistImage");
	}


  public int frRate;
  public ArrayList<Integer> pixels;

	
	public void settings() {
		size(28*20, 28*20);
	}


	public void setup() {
		frRate = 5;
		frameRate(frameRate);
    pixels = new ArrayList<>();
    // the handwritten number "7"
    pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0);
    pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0);
    pixels.add(0); pixels.add(0); pixels.add(84); pixels.add(185); pixels.add(159); pixels.add(151); pixels.add(60); pixels.add(36); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(222); pixels.add(254); pixels.add(254); pixels.add(254); pixels.add(254); pixels.add(241); pixels.add(198); pixels.add(198); pixels.add(198); pixels.add(198); pixels.add(198); pixels.add(198); pixels.add(198); pixels.add(198); pixels.add(170); pixels.add(52); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(67); pixels.add(114); pixels.add(72); pixels.add(114); pixels.add(163); pixels.add(227); pixels.add(254); pixels.add(225); pixels.add(254); pixels.add(254); pixels.add(254); pixels.add(250); pixels.add(229); pixels.add(254); pixels.add(254); pixels.add(140); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(17); pixels.add(66); pixels.add(14); pixels.add(67); pixels.add(67); pixels.add(67); pixels.add(59); pixels.add(21); pixels.add(236);
    pixels.add(254); pixels.add(106); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(83); pixels.add(253); pixels.add(209); pixels.add(18); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(22); pixels.add(233); pixels.add(255); pixels.add(83); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(129); pixels.add(254); pixels.add(238); pixels.add(44); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0);
    pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(59); pixels.add(249); pixels.add(254); pixels.add(62); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(133); pixels.add(254); pixels.add(187); pixels.add(5); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(9); pixels.add(205); pixels.add(248); pixels.add(58); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(126); pixels.add(254); pixels.add(182); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0);
    pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(75); pixels.add(251); pixels.add(240); pixels.add(57); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(19); pixels.add(221); pixels.add(254); pixels.add(166); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(3); pixels.add(203); pixels.add(254); pixels.add(219); pixels.add(35); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0);
    pixels.add(38); pixels.add(254); pixels.add(254); pixels.add(77); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(31); pixels.add(224); pixels.add(254); pixels.add(115); pixels.add(1); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(133); pixels.add(254); pixels.add(254); pixels.add(52); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(61); pixels.add(242); pixels.add(254); pixels.add(254); pixels.add(52); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0);
    pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(121); pixels.add(254); pixels.add(254); pixels.add(219); pixels.add(40); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(121); pixels.add(254); pixels.add(207); pixels.add(18); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0); pixels.add(0);
	}

	
	public void draw() {
    background(200);

    int ix = 0;
    int iy = 0;
    for(int k = 0; k < 28*28; k++) {
      fill(pixels.get(k));
      stroke(pixels.get(k));
      rect(ix*(width/28), iy*(height/28), width/28, height/28);
      ix++;
      if(ix % 28 == 0) {
        ix = 0;
        iy++;
      }
    }
	}

}
